DijkstraAlgorithm.Web/Controllers/baseController.cs
using System.Web.Mvc;
using Cassette.Views;
using DijkstraAlgorithm.Web.Extension;
using DijkstraAlgorithm.Web.Infra.ActionResults;
using MvcSiteMapProvider;

namespace DijkstraAlgorithm.Web.Controllers
{
    public abstract class baseController : Controller
    {
		protected override void OnResultExecuting(ResultExecutingContext filterContext)
		{
			Bundles.Reference("Content");
			Bundles.Reference("Scripts/jquery-1.7.2.min.js", "top");
			Bundles.Reference("Scripts");

			var controllerName = filterContext.RouteData.GetRequiredString("Controller");
			var actionName = filterContext.RouteData.GetRequiredString("Action");
			
			string urlBundle = "{0}/Controllers/{1}/{2}.{3}";
			var jsFile = string.Format(urlBundle, "Scripts", controllerName, actionName, "js");
			var cssFile = string.Format(urlBundle, "Content", controllerName, actionName, "css");
			
			if (System.IO.File.Exists(Server.MapPath("~/" + jsFile)))
				Bundles.Reference(jsFile, "page");
			if (System.IO.File.Exists(Server.MapPath("~/" + cssFile)))
				Bundles.Reference(cssFile, "page");

			base.OnResultExecuting(filterContext);
		}

		protected override void OnActionExecuting(ActionExecutingContext filterContext)
		{
			ViewBag.Title = this.GetCurrentSiteMapNode().TitlePage();
			base.OnActionExecuting(filterContext);
		}

		protected internal GraphProcessedJsonResult GraphProcessedJson(IProcessGraph graphProcessed)
		{
			return new GraphProcessedJsonResult(graphProcessed);
		}
    }
}

DijkstraAlgorithm.Web/Controllers/homeController.cs
using System.Web.Mvc;

namespace DijkstraAlgorithm.Web.Controllers
{
	[OutputCache(CacheProfile = "Fixed")]
	public class homeController : baseController
    {
        public ActionResult index()
        {
            return View();
        }
    }
}

DijkstraAlgorithm.Web/Controllers/mapController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DijkstraAlgorithm.Model;
using DijkstraAlgorithm.Repository;
using DijkstraAlgorithm.Web.Infra.ActionResults;

namespace DijkstraAlgorithm.Web.Controllers
{
    public class mapController : baseController
    {
		private readonly IRepository _repository;
		public mapController(IRepository repository)
		{
			_repository = repository;
		}

        public ActionResult index(string search)
        {
			var query = _repository.Query<Map>();
			if (!string.IsNullOrWhiteSpace(search))
			{
				search = search.ToLower();
				query = query.Where(p => p.Name == search);
			}

			return View(query.OrderByDescending(p => p.DateAdded).ToList());
        }

		[OutputCache(CacheProfile = "Fixed")]
		public ActionResult create()
		{
			return View();
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		public ActionResult create(Map model)
		{
			if (ModelState.IsValid)
			{
				if (!_repository.Query<Map>().Any(p => p.Name == model.Name))
				{
					_repository.Store(model);
					_repository.SaveChanges();
					return RedirectToAction("details", new { id= model.Id });
				}
				ModelState.AddModelError("name", "Name already exists!");
			}

			return View(model);
		}

		[OutputCache(CacheProfile = "Fixed")]
		public ActionResult details(int id)
		{
			var model = _repository.Get<Map>(id);
			if (model == null)
				return HttpNotFound("Map not found.");
			return View(model);
		}

		[HttpPost]
		[OutputCache(CacheProfile = "Fixed")]
		public GraphProcessedJsonResult route(Graph graph, IList<string> steps)
		{
			if (steps == null || steps.Count < 2)
			{
				Response.StatusCode = 406;
				Response.StatusDescription = "You must select at least two vertices to calculate a route";
				return null;
			}
			var x = new MultiProcessGraph(graph, steps.ToArray());
			return GraphProcessedJson(x);
		}
    }
}

DijkstraAlgorithm.Web/Views/Shared/DisplayTemplates/MenuHelperModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.MenuHelperModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			@Html.ActionLink("Dijkstra Algorithm", "Index", "Home", null, new { @class = "brand" })
			<ul class="nav">
				@foreach (var node in Model.Nodes)
				{
					var hasChild = node.Children.Any();
					<li class="@(node.IsInCurrentPath ? "active" : "")@(hasChild ? "dropdown" : "")">
						@Html.DisplayFor(m => node, "SiteMapMenuNodeModel")
						@if (hasChild)
						{
							@Html.DisplayFor(m => node.Children, "SiteMapMenuNodeModelList", new { ulClass = "dropdown-menu" })
						}
					</li>
				}
			</ul>

			<ul class="nav pull-right">
				<li>
					@using (Html.BeginForm("index", "map", FormMethod.Get, new { @class = "form-search navbar-search pull-right", id = "form-searchmap" }))
					{
						<input type="text" name="search" id="search" class="search-query span2" placeholder="Search for map" />
					}
				</li>
			</ul>

		</div>
	</div>
</div>

DijkstraAlgorithm.Web/Views/Shared/DisplayTemplates/SiteMapHelperModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.SiteMapHelperModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

<ul class="siteMap">
    @foreach (var node in Model.Nodes) { 
        <li>@Html.DisplayFor(m => node) 
            @if (node.Children.Any()) {
                @Html.DisplayFor(m => node.Children)
            }
        </li>
    }
</ul>

DijkstraAlgorithm.Web/Views/Shared/DisplayTemplates/SiteMapMenuNodeModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.SiteMapNodeModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

@helper RenderDropdown()
{
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        @Model.Title
        <b class="caret"></b>
    </a>
}

@if (Model.IsClickable)
{
    if (Model.Children.Any()) {
        @RenderDropdown()
    } else {
        <a href="@Model.Url">@Model.Title</a>
    }
}
else
{
    if (Model.Children.Any()) {
        @RenderDropdown()
    } else {
        <p class="navbar-text">@Model.Title</p>
    }
    
}

DijkstraAlgorithm.Web/Views/Shared/DisplayTemplates/SiteMapMenuNodeModelList.cshtml
@model MvcSiteMapProvider.Web.Html.Models.SiteMapNodeModelList
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models
@{
    object ulClass;
    if (!ViewData.TryGetValue("ulClass", out ulClass))
    {
        ulClass = "";
    }
    
}

<ul class="@ulClass">
    @foreach (var node in Model) { 
        <li>@Html.DisplayFor(m => node) 
            @if (node.Children.Any()) {
                @Html.DisplayFor(m => node.Children)
            }
        </li>
    }
</ul>

DijkstraAlgorithm.Web/Views/Shared/DisplayTemplates/SiteMapNodeModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.SiteMapNodeModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

@if (Model.IsClickable)
{
    <a href="@Model.Url">@Model.Title</a>
}
else
{
    @Model.Title
}

DijkstraAlgorithm.Web/Views/Shared/DisplayTemplates/SiteMapNodeModelList.cshtml
@model MvcSiteMapProvider.Web.Html.Models.SiteMapNodeModelList
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

<ul>
    @foreach (var node in Model) { 
        <li>@Html.DisplayFor(m => node) 
            @if (node.Children.Any()) {
                @Html.DisplayFor(m => node.Children)
            }
        </li>
    }
</ul>

DijkstraAlgorithm.Web/Views/Shared/DisplayTemplates/SiteMapPathHelperModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.SiteMapPathHelperModel
@using System.Web.Mvc.Html
@using System.Linq
@using MvcSiteMapProvider.Web.Html.Models

<ul id="sitemap-path" class="breadcrumb">
	@foreach (var node in Model)
	{ 
		<li class="@( node.IsCurrentNode ? "active" : "")">
			@Html.DisplayFor(m => node, "SiteMapPathNodeModel")
    
			@if (node != Model.Last())
			{
				<span class="divider">/</span>
			}
		</li>
	}
</ul>

DijkstraAlgorithm.Web/Views/Shared/DisplayTemplates/SiteMapPathNodeModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.SiteMapNodeModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

<a href="@Model.Url">@Model.Title</a>

DijkstraAlgorithm.Web/Views/Shared/DisplayTemplates/SiteMapTitleHelperModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.SiteMapTitleHelperModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

<h1>@Model.CurrentNode.Title <small>@Model.CurrentNode.Description</small></h1>

DijkstraAlgorithm.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="pt-br">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0">
	<meta name="charset" content="utf-8" />
    <meta name="autor" content="Riderman" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-language" content="pt,pt-BR" />

	<link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/favicon.ico" type="image/x-icon">

    <title>@ViewBag.Title</title>

	@* Style Sheet *@
	@Bundles.RenderStylesheets("top")
	@Bundles.RenderStylesheets()
	@Bundles.RenderStylesheets("vendor")
	@Bundles.RenderStylesheets("page")
	@RenderSection("css", false)
</head>
<body>
	<!--[if lt IE 7]> 
		<div style=' clear: both; height: 59px; padding:0 0 0 15px; position: relative;'> <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode"><img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0010_portuguese.jpg" stype="border=0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." /></a></div>
	<![endif]-->

	@Html.MvcSiteMap().Menu(false)

	<div class="container">
		@if (IsSectionDefined("sitemap"))
		{
			@RenderSection("sitemap", false)
		}
		else
		{
			@Html.MvcSiteMap().SiteMapPath()
		}

		<div id="wrap-body">
			@RenderBody()
		</div>

	</div>

	@* Scripts *@
	@Bundles.RenderScripts("top")
	@Bundles.RenderScripts()
	@Bundles.RenderScripts("vendor")
	@Bundles.RenderScripts("page")
	@RenderSection("js", false)
	@if (!Context.IsDebuggingEnabled)
	{
		<script type="text/javascript">

			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-34073168-1']);
			_gaq.push(['_setDomainName', 'dijkstrasalgorithm.apphb.com']);
			_gaq.push(['_trackPageview']);

			(function () {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();

		</script>
	}

    <!--[if (gte IE 6)&(lte IE 8)]>
        <script src="~/Scripts/selectivizr-min.js" type="text/javascript"></script>
    <![endif]-->

	<script src="//static.getclicky.com/js" type="text/javascript"></script>
	<script type="text/javascript">try { clicky.init(100617078); } catch (e) { }</script>
	<noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/100617078ns.gif" /></p></noscript>

</body>
</html>

DijkstraAlgorithm.Web/Views/home/index.cshtml
@section sitemap {}

<div class="row-fluid">
	<div class="span12">
		<div class="hero-unit">
			<h1>Shortest route</h1>
			<p>This application uses the <a href="http://en.wikipedia.org/wiki/Dijkstra's_algorithm" target="_blank">Dijkstra algorithm</a> to calculate the shortest distance between two points.</p>
			<p>
				@Html.ActionLink("Create", "create", "map", null, new { @class = "btn btn-large btn-primary", id = "create-map" })
				@Html.ActionLink("Maps", "index", "map", null, new { @class = "btn btn-large", id = "search-map" })
			</p>
		</div>
		<div class="row-fluid">
			<div class="span6">
				<h2>How it works</h2>
				<dl>
					<dt>Maps to be used</dt>
					<dd>Create maps with directions and distances between the points to use and share with the community.</dd>
					<dt>Calculating the distance</dt>
					<dd>Select the map for the system to calculate the shortest distance between two points.</dd>
					<dt>Calculating the path</dt>
					<dd>Select the map for the system to calculate the shortest path between two points.</dd>
				</dl>
			</div>

			<div class="span6">
				<h2>Get Started</h2>
				<p>You can start by creating a map, or selecting an existing map in our database.</p>

				<h4>Create map</h4>
				<p>In the top menu</p>
				<ul>
					<li>Click in <span class="label label-inverse">Maps</span></li>
					<li>Click in <span class="label label-inverse">Create</span></li>
					<li>Click to add a point or drag to connect two points.</li>
				</ul>

				<h4>Find route in map</h4>
				<p>In the top menu</p>
				<ul>
					<li>Click in <span class="label label-inverse">Maps</span></li>
					<li>Click in <span class="label label-inverse">List</span></li>
					<li>Select the map to find a route.</li>
				</ul>

				<h4>Search map</h4>
				<p>In the top menu</p>
				<ul>
					<li>Enter map name in <span class="label label-inverse">Search for map</span> field.</li>
					<li>Hit <span class="label label-inverse">enter</span> to find a map by name.</li>
				</ul>
			</div>
		</div>
	</div>
</div>

DijkstraAlgorithm.Web/Views/map/EditorTemplates/Map.cshtml
@model Map

@Html.HiddenFor(p => p.GraphJson)
<div class="input-append">
	@Html.TextBoxFor(p => p.Name, new { @class = "input-small", placeholder = "Map name" })
	<button id="save-map" type="button" class="btn btn-small btn btn-primary">Save</button>
</div>

DijkstraAlgorithm.Web/Views/map/create.cshtml
@model Map
@{
	Bundles.Reference("Scripts/Vendors/kinetic-v4.4.3.min.js");
}

@Html.MvcSiteMap().SiteMapTitle()

<div class="btn-group pull-right">
	@using (Html.BeginForm("create", "map", FormMethod.Post, new { @class = "form-inline", id = "form-map" }))
	{
		@Html.AntiForgeryToken()
		@Html.EditorForModel()
	}
</div>


<span id="prompt-distances" class="checkbox">
	<input type="checkbox" />
	Prompt distances
</span>

<div id="map"></div>


Graph: <input class="input-large" id="text-graph" name="Name" placeholder="Eg. AB5 BC2 CD3 > enter to apply" type="text" value="">
<button id="reset-map" class="btn btn-small btn-danger pull-right">Clean</button>	



DijkstraAlgorithm.Web/Views/map/details.cshtml
@model Map
@{
	Bundles.Reference("Scripts/Vendors/kinetic-v4.4.3.min.js");
	Bundles.Reference("Scripts/Vendors/jquery.buildr.min.js");
}

@Html.MvcSiteMap().SiteMapTitle()
@Html.HiddenFor(p => p.Id)
@Html.HiddenFor(p => p.GraphJson)

<div id="message"></div>

<button id="calcule-route" class="btn btn-primary">Calculate route</button>

<div id="map"></div>

DijkstraAlgorithm.Web/Views/map/index.cshtml
@model IEnumerable<Map>
@Html.MvcSiteMap().SiteMapTitle()

@Html.ActionLink("Create map", "create", "map", null, new { @class="btn" })

<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Created</th>
		</tr>
	</thead>

	<tbody>
		@foreach (var map in Model)
		{
			<tr>
				<td>@Html.ActionLink(map.Name != null ? map.Name : "<no name>", "details", new { id=map.Id })</td>
				<td>@map.DateAdded.ToShortDateString()</td>
			</tr>
		}
	</tbody>

</table>